apiVersion: v1
kind: Service
metadata:
  name: example-service-nginx
  labels:
    name: example-service-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: example-service-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    name: example-service
    instance: testing
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    name: example-service